
// Courses
export const GET_COURSES_START = "GET_COURSES_START";
export const GET_COURSES_SUCCESS = "GET_COURSES_SUCCESS";
export const GET_COURSES_FAILURE = "GET_COURSES_FAILURE";

// Course
export const SHOW_COURSE_START = "SHOW_COURSE_START";
export const SHOW_COURSE_SUCCESS = "SHOW_COURSE_SUCCESS";
export const SHOW_COURSE_FAILURE = "SHOW_COURSE_FAILURE";
