// Courses
export const GET_COURSES_START = 'GET_COURSES_START'
export const GET_COURSES_SUCCESS = 'GET_COURSES_SUCCESS'
export const GET_COURSES_FAILURE = 'GET_COURSES_FAILURE'

// Course
export const SHOW_COURSE_START = 'SHOW_COURSE_START'
export const SHOW_COURSE_SUCCESS = 'SHOW_COURSE_SUCCESS'
export const SHOW_COURSE_FAILURE = 'SHOW_COURSE_FAILURE'
export const SET_COURSE_ID = 'SET_COURSE_ID'

// Chats
export const GET_CHATS_START = 'GET_CHATS_START'
export const GET_CHATS_SUCCESS = 'GET_CHATS_SUCCESS'
export const GET_CHATS_FAILURE = 'GET_CHATS_FAILURE'

// Chat
export const ADD_CHAT_START = 'ADD_CHAT_START'
export const ADD_CHAT_SUCCESS = 'ADD_CHAT_SUCCESS'
export const ADD_CHAT_FAILURE = 'ADD_CHAT_FAILURE'
export const RESET_CHATS = 'RESET_CHATS'
